Attribute VB_Name = "Bas_PublicVariables"
Public UPDATE_URL As String
Public UPDATE_SETTINGS As String
Public SMTP_SERVER As String
Public SMTP_PORT As String
Public SMTP_USERNAME As String
Public SMTP_PASSWORD As String
Public DISPLAY_NAME As String
Public REPLY_ADDRESS As String
Public RECIPIENT_NAME As String
Public RECIPIENT_ADDRESS As String
